# MoodBridge DevOps Configuration
# Comprehensive automation and process configuration

version: "1.0"
project_name: "MoodBridge_Rust"
created: "2025-06-30"

# Repository Configuration
repositories:
  primary:
    path: "/private/tmp/MoodBridge_Rust"
    branch_strategy: "main"
    auto_sync: true
  
  backup:
    path: "/Users/tyler/Library/Mobile Documents/com~apple~CloudDocs/Legal/MoodBridge_Rust"
    branch_strategy: "main"
    auto_sync: true

  related_projects:
    - path: "/Users/tyler/Desktop/DevCopilot-Pro"
      type: "dependency"
    - path: "/Users/tyler/Desktop/JPMC_Zero_Trust"
      type: "reference"
    - path: "/Users/tyler/Desktop/MoodBridge-LangChain-API"
      type: "integration"

# Commit Standards
commit_standards:
  message_format: "conventional"
  types:
    - "feat"      # New features
    - "fix"       # Bug fixes
    - "docs"      # Documentation changes
    - "style"     # Code style changes
    - "refactor"  # Code refactoring
    - "test"      # Test changes
    - "chore"     # Maintenance tasks
    - "security"  # Security updates
    - "perf"      # Performance improvements
  
  required_elements:
    - type
    - description
    - scope (optional)
    - issue_reference (when applicable)

# Automated Checks
automated_checks:
  pre_commit:
    - rust_format: true
    - rust_clippy: true
    - cargo_check: true
    - documentation_check: true
    - todo_scan: true
    - security_scan: true
  
  pre_push:
    - test_suite: true
    - integration_tests: true
    - documentation_build: true
    - dependency_audit: true

# Documentation Requirements
documentation:
  required_files:
    - "README.md"
    - "CHANGELOG.md"
    - "docs/API.md"
    - "docs/DEPLOYMENT.md"
    - "docs/CONTRIBUTING.md"
  
  auto_generation:
    - api_docs: true
    - rust_docs: true
    - architecture_diagrams: false
  
  update_triggers:
    - new_features
    - api_changes
    - security_updates
    - dependency_updates

# Quality Gates
quality_gates:
  code_coverage:
    minimum: 80
    target: 90
  
  security:
    vulnerability_scan: true
    dependency_scan: true
    secret_detection: true
  
  performance:
    benchmark_regression: false
    memory_leak_detection: true

# Automation Scripts
automation:
  commit_checker: "./devops_commit_checker.sh"
  pre_commit_hook: "./.git/hooks/pre-commit"
  deployment_script: "./scripts/deploy.sh"
  backup_script: "./scripts/backup.sh"

# Notification Settings
notifications:
  channels:
    - type: "console"
      level: "info"
  
  events:
    - uncommitted_changes
    - failed_tests
    - security_alerts
    - deployment_completion

# Integration Settings
integrations:
  github:
    enabled: false
    auto_pr: false
  
  ci_cd:
    enabled: false
    platform: "github_actions"
  
  monitoring:
    enabled: true
    local_only: true

# Backup Strategy
backup:
  frequency: "daily"
  retention: "30_days"
  locations:
    - "/Users/tyler/Library/Mobile Documents/com~apple~CloudDocs/Legal/MoodBridge_Rust"
  
  exclude_patterns:
    - "target/"
    - "*.log"
    - ".DS_Store"
    - "node_modules/"

# Environment Configuration
environments:
  development:
    auto_test: true
    documentation_build: true
  
  production:
    approval_required: true
    backup_before_deploy: true
    rollback_strategy: "automatic"
