use super::*;

pub struct SelfImprovementEngine;

impl SelfImprovementEngine {
    pub fn new() -> Self {
        Self
    }

    pub async fn generate_insights(&self, activity: &DevelopmentActivity) -> Result<Vec<ActivityInsight>, WarpCommandError> {
        // Return the insights already generated by the activity tracker
        Ok(activity.ai_insights.clone())
    }
}
