/// Legal Disclaimers for MoodBridge_Rust Platform
/// 
/// This module contains comprehensive legal disclaimers and warnings for all
/// potentially sensitive legal operations within the platform.

use serde::{Deserialize, Serialize};

/// General legal disclaimer for the platform
pub const GENERAL_DISCLAIMER: &str = r#"
⚖️ LEGAL DISCLAIMER - IMPORTANT NOTICE ⚖️

This software is a technology tool and does NOT provide legal advice. 
The information generated by this system is for informational purposes only 
and should not be relied upon as legal advice. 

ALWAYS consult with a qualified attorney licensed in your jurisdiction 
for specific legal advice regarding your situation.

By using this system, you acknowledge that:
• This is not a substitute for professional legal counsel
• No attorney-client relationship is created
• You use this system at your own risk and discretion
• The developers and operators are not liable for legal consequences

Continue only if you understand and accept these terms.
"#;

/// AI Legal Advice Disclaimer - Critical Warning
pub const AI_LEGAL_ADVICE_DISCLAIMER: &str = r#"
🚨 CRITICAL LEGAL WARNING - AI LEGAL ASSISTANCE 🚨

⚠️ THIS AI SYSTEM DOES NOT PROVIDE LEGAL ADVICE ⚠️

This artificial intelligence system is designed to assist with legal technology
tasks but CANNOT and DOES NOT provide legal advice, legal opinions, or 
legal strategy recommendations.

MANDATORY ACKNOWLEDGMENTS:
✓ This AI is NOT a licensed attorney
✓ This AI CANNOT practice law in any jurisdiction
✓ This AI's responses are NOT legal advice
✓ Attorney supervision is REQUIRED for legal matters
✓ Professional liability insurance does NOT cover AI advice

LEGAL COMPLIANCE REQUIREMENTS:
• All AI outputs MUST be reviewed by a licensed attorney
• No legal decisions should be based solely on AI responses
• Attorney-client privilege may be compromised without proper safeguards
• Professional responsibility rules require attorney oversight

By proceeding, you certify that:
1. You understand this is NOT legal advice
2. You will seek qualified legal counsel for legal matters
3. You accept full responsibility for any consequences
4. An attorney will review any legal applications of this output

VIOLATION OF THESE TERMS MAY RESULT IN LEGAL CONSEQUENCES.
"#;

/// Voice Recording Disclaimer
pub const VOICE_RECORDING_DISCLAIMER: &str = r#"
🎤 VOICE RECORDING LEGAL NOTICE 🎤

This system may record, store, and process your voice communications.

IMPORTANT PRIVACY AND LEGAL CONSIDERATIONS:
• Voice recordings may be subject to legal discovery
• Attorney-client privilege may be affected
• Consent of all parties may be required by law
• Recordings may be retained for legal compliance purposes

CONSENT REQUIREMENTS:
By proceeding, you confirm that:
✓ You consent to voice recording and processing
✓ You have authority to consent for all participants
✓ You understand privilege implications
✓ You comply with applicable recording laws in your jurisdiction

If this involves attorney-client communications, ensure:
• Your attorney has approved this recording method
• Proper privilege protections are in place
• The recording serves a legitimate legal purpose

WARNING: Recording without proper consent may violate federal and state laws.
"#;

/// Document Modification Disclaimer
pub const DOCUMENT_MODIFICATION_DISCLAIMER: &str = r#"
📄 DOCUMENT MODIFICATION LEGAL WARNING 📄

You are about to modify legal documents using an automated system.

CRITICAL LEGAL CONSIDERATIONS:
⚠️ Evidence Integrity: Modifying legal documents may affect their evidentiary value
⚠️ Chain of Custody: Proper documentation of changes is legally required
⚠️ Authentication: Digital modifications may complicate document authentication
⚠️ Professional Responsibility: Attorney oversight may be required

MANDATORY SAFEGUARDS:
• Document version control and audit trails
• Digital signatures and timestamps
• Backup copies of original documents
• Attorney review of modifications
• Compliance with court rules and procedures

POTENTIAL LEGAL CONSEQUENCES:
- Evidence may be excluded from legal proceedings
- Sanctions for improper document handling
- Malpractice liability for inadequate procedures
- Criminal liability for evidence tampering

By proceeding, you acknowledge:
1. You understand the legal risks of document modification
2. You will implement proper safeguards
3. You will obtain attorney approval when required
4. You accept responsibility for compliance with all applicable rules

PROCEED ONLY WITH PROPER LEGAL AUTHORIZATION.
"#;

/// Client Data Processing Disclaimer
pub const CLIENT_DATA_DISCLAIMER: &str = r#"
🔒 CLIENT DATA PROCESSING LEGAL NOTICE 🔒

This system will process confidential client information.

CONFIDENTIALITY AND PRIVILEGE PROTECTIONS:
• Attorney-client privilege must be maintained
• Work product doctrine protections required
• Confidentiality rules strictly enforced
• Data security measures mandatory

REGULATORY COMPLIANCE REQUIRED:
✓ GDPR (European Union data protection)
✓ CCPA (California privacy rights)
✓ HIPAA (if health information involved)
✓ State confidentiality requirements
✓ Professional responsibility rules

DATA HANDLING REQUIREMENTS:
• Encrypted storage and transmission
• Limited access on need-to-know basis
• Audit logging of all data access
• Secure deletion when appropriate
• Breach notification procedures

PROFESSIONAL RESPONSIBILITY:
Attorneys must ensure:
- Competent technology use (Model Rule 1.1)
- Reasonable confidentiality measures (Model Rule 1.6)
- Proper supervision of technology (Model Rule 5.3)

WARNING: Improper handling of client data may result in:
- Professional discipline
- Malpractice liability
- Regulatory penalties
- Loss of privilege protections

Continue only with proper authorization and safeguards.
"#;

/// PowerPoint/Presentation Generation Disclaimer
pub const PRESENTATION_GENERATION_DISCLAIMER: &str = r#"
🎨 AI PRESENTATION GENERATION LEGAL NOTICE 🎨

This system generates presentations using artificial intelligence.

CONTENT ACCURACY WARNINGS:
⚠️ AI-generated content may contain errors
⚠️ Legal information may be incomplete or outdated
⚠️ Statistical representations may be misleading
⚠️ Professional review is required

PROFESSIONAL LIABILITY CONSIDERATIONS:
• All AI-generated content must be verified
• Attorney review required for legal presentations
• Fact-checking mandatory before client use
• Source citation and attribution required

MISREPRESENTATION RISKS:
- Inaccurate legal statements
- Misleading statistical analysis
- Unauthorized practice of law implications
- Professional responsibility violations

By using AI-generated presentations, you agree to:
1. Thoroughly review all content for accuracy
2. Verify all legal statements and citations
3. Obtain attorney approval for legal content
4. Accept responsibility for all representations made

This tool assists with presentation creation but does not ensure accuracy or completeness.
"#;

/// Semantic Search Disclaimer
pub const SEMANTIC_SEARCH_DISCLAIMER: &str = r#"
🔍 LEGAL DOCUMENT SEARCH NOTICE 🔍

This AI-powered search system analyzes legal documents and data.

SEARCH LIMITATIONS:
• AI may miss relevant information
• Search results may be incomplete
• Privilege protections must be maintained
• Manual review remains essential

DISCOVERY AND PRIVILEGE CONSIDERATIONS:
⚠️ Search queries may be discoverable
⚠️ Results may inadvertently expose privileged information
⚠️ Proper privilege review protocols required
⚠️ Opposing counsel may seek search methodologies

PROFESSIONAL COMPETENCE REQUIREMENTS:
Attorneys must ensure:
- Understanding of search technology capabilities and limitations
- Proper privilege screening procedures
- Adequate quality control measures
- Compliance with discovery obligations

Do not rely solely on AI search results for legal analysis or discovery responses.
"#;

/// Collaboration Metrics Disclaimer
pub const COLLABORATION_METRICS_DISCLAIMER: &str = r#"
📊 TEAM COLLABORATION METRICS LEGAL NOTICE 📊

This system analyzes team performance and collaboration data.

EMPLOYMENT LAW CONSIDERATIONS:
⚠️ Performance monitoring may be subject to labor laws
⚠️ Privacy rights of employees must be respected
⚠️ Discrimination concerns in performance evaluation
⚠️ Union notification requirements may apply

DATA PRIVACY REQUIREMENTS:
• Employee consent for monitoring may be required
• Personal data protection laws apply
• Data retention and deletion policies needed
• Access controls and audit trails mandatory

PROFESSIONAL RESPONSIBILITY:
• Fair and non-discriminatory use of metrics
• Transparency in evaluation criteria
• Protection of attorney-client privileged communications
• Compliance with firm policies and procedures

Use collaboration metrics responsibly and in compliance with all applicable laws.
"#;

/// Timeline Analysis Disclaimer
pub const TIMELINE_ANALYSIS_DISCLAIMER: &str = r#"
📅 LEGAL TIMELINE ANALYSIS NOTICE 📅

This system generates legal case timelines using AI analysis.

ACCURACY AND COMPLETENESS WARNINGS:
⚠️ AI may misinterpret chronological relationships
⚠️ Critical dates or events may be omitted
⚠️ Timeline accuracy must be independently verified
⚠️ Professional review is mandatory

DISCOVERY AND STRATEGY IMPLICATIONS:
• Timelines may constitute attorney work product
• Privilege protections must be maintained
• Discovery obligations may be affected
• Strategic analysis requires attorney oversight

EVIDENTIARY CONSIDERATIONS:
- Foundation requirements for timeline evidence
- Authentication challenges for AI-generated timelines
- Hearsay and reliability concerns
- Expert testimony may be required

By using AI timeline analysis, you acknowledge:
1. Independent verification of all dates and events is required
2. Attorney review and approval is necessary
3. Proper privilege protections must be maintained
4. You accept responsibility for timeline accuracy

Do not rely solely on AI-generated timelines for legal strategy or evidence.
"#;

/// Helper struct for managing disclaimers
#[derive(Debug, Serialize, Deserialize)]
pub struct DisclaimerManager {
    pub disclaimers_shown: std::collections::HashMap<String, Vec<String>>,
    pub acknowledgments_required: Vec<String>,
}

impl DisclaimerManager {
    pub fn new() -> Self {
        Self {
            disclaimers_shown: std::collections::HashMap::new(),
            acknowledgments_required: Vec::new(),
        }
    }

    /// Record that a user has been shown a specific disclaimer
    pub fn record_disclaimer_shown(&mut self, user_id: &str, disclaimer_type: &str) {
        self.disclaimers_shown
            .entry(user_id.to_string())
            .or_insert_with(Vec::new)
            .push(disclaimer_type.to_string());
    }

    /// Check if a user has acknowledged a specific disclaimer
    pub fn has_acknowledged_disclaimer(&self, user_id: &str, disclaimer_type: &str) -> bool {
        self.disclaimers_shown
            .get(user_id)
            .map(|disclaimers| disclaimers.contains(&disclaimer_type.to_string()))
            .unwrap_or(false)
    }

    /// Get the appropriate disclaimer text for an operation
    pub fn get_disclaimer(&self, operation_type: &str) -> &'static str {
        match operation_type {
            "ai_legal_advice" => AI_LEGAL_ADVICE_DISCLAIMER,
            "voice_recording" => VOICE_RECORDING_DISCLAIMER,
            "document_modification" => DOCUMENT_MODIFICATION_DISCLAIMER,
            "client_data" => CLIENT_DATA_DISCLAIMER,
            "presentation_generation" => PRESENTATION_GENERATION_DISCLAIMER,
            "semantic_search" => SEMANTIC_SEARCH_DISCLAIMER,
            "collaboration_metrics" => COLLABORATION_METRICS_DISCLAIMER,
            "timeline_analysis" => TIMELINE_ANALYSIS_DISCLAIMER,
            _ => GENERAL_DISCLAIMER,
        }
    }
}
